services:
  backend:
    build: ./backend
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./backend:/app
    ports:
      - 8001:8001
    networks:
      - digital_library

  frontend:
    build: ./frontend
    ports:
      - "67:67"
    networks:
      - digital_library

networks:
  digital_library:
    driver: bridge
